### ISSUE TITLE
Report Access Rights don't work for Show Tables screen

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/reports#104]
### Environment

- Platform version: 6.10-SNAPSHOT

### Description of the bug or enhancement

- Import the sample-library attached
- createDb
- Import Reports.zip
- Check that user Vasya has role Role for Vasya
- Add [Role for Vasya] for one report and [Vasya denied] role for another report
- Add table templates for all reports
- Login as vasya (password admin) and open Reports -> Show Tables

AR:
Vasya sees and can run all reports

ER:
Only one report with [Role for Vasya] assigned is available

See also:
https://www.cuba-platform.com/discuss/t/roles-do-not-work-correctly-on-the-show-table-screen/6552

[sample-library.zip](https://github.com/cuba-platform/reports/files/2414509/sample-library.zip)
[Reports.zip](https://github.com/cuba-platform/reports/files/2414510/Reports.zip)

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[7d2454a8](https://git.haulmont.com/platform/reports/commit/7d2454a8030634cd62af9e78baaf857921c1eb90) in **release_6_10** - Report Access Rights don't work for Show Tables screen #104
