### ISSUE TITLE
Wizard screen for reports creating cannot be closed

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/reports#108]
#### Environment

- Platform version: 7.0

#### Description of the bug or enhancement
1. Add a reports to the app
2. Open reports screen and create a new one using wizard
3. Try to close the wizard screen

![RVUsaor6uF.gif](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/1fcd9100-fd5e-43fe-b28a-b9e1f8d8fa62)

**Comment by jreznot** [comment]
Fixed in https://github.com/cuba-platform/cuba/issues/1354
