### ISSUE TITLE
Introduce app property for old TAB behaviour in DataSet script editor

### ISSUE THREAD

**Issue by Quicksy** [cuba-platform/reports#112]
'Tab' button moves cursor to next field instead of adding tab spacing in report editor

### Environment

- Platform version: 6.8.12
- Client type: Web
- Browser: Chrome, Firefox, etc.

### Description of the bug or enhancement

- Minimal reproducible example
Open any report, select band, click in 'script' editor section, press 'Tab'.
- Expected behavior
Tab spacing added.
- Actual behavior
Cursor moved to another text field, no tab spacing.

**Comment by jreznot** [comment]
Hi, this behavior is intentional. It is required in order to have ability to move focus to prev/next field in the form.
If you want to use Tab - use extended source editing mode: 

![image](https://user-images.githubusercontent.com/1066152/46716475-38252b00-cc75-11e8-902f-0ece6a7c3b44.png)

Use `Full screen` link.

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[9208edb1](https://git.haulmont.com/platform/reports/commit/9208edb10a967255da356154935e18d17e8c6871) in **master** - Introduce app property for old TAB behaviour in DataSet script editor #112

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[9a129321](https://git.haulmont.com/platform/reports/commit/9a129321f73655b1ed86328f99ded0bc4f3a90a1) in **release_6_10** - Introduce app property for old TAB behaviour in DataSet script editor #112

**Comment by jreznot** [comment]
Added **reporting.enableTabSymbolInDataSetEditor** application property.

Set true for old behavior:
```
reporting.enableTabSymbolInDataSetEditor = true
```

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[fe3ee104](https://git.haulmont.com/platform/reports/commit/fe3ee1044a6ad0745a4e81dd3e3523a603405624) in **release_6_9** - Introduce app property for old TAB behaviour in DataSet script editor #112

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[0e054376](https://git.haulmont.com/platform/reports/commit/0e054376d157cd9a9455d77d138d69b1651cdd5f) in **release_6_8** - Introduce app property for old TAB behaviour in DataSet script editor #112

**Comment by jreznot** [comment]
Added **reporting.enableTabSymbolInDataSetEditor** application property.

Set true for old behavior in web-app.properties:
```
reporting.enableTabSymbolInDataSetEditor = true
```
