### ISSUE TITLE
Missing captions for actions in ReportBrowser

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/reports#113]
### Environment

- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

![image.png](https://images.zenhubusercontent.com/5ae3309c4b5806bc2bd0e8d8/95e92f93-ccba-4780-b92b-291aff41549d)

There should be `Copy` and `Run` captions on buttons.

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[c58f9337](https://git.haulmont.com/platform/reports/commit/c58f9337584f8087d24c07c65bd36dd35474e3df) in **master** - Missing captions for actions in ReportBrowser #113
