### ISSUE TITLE
ClassCastException occurred while trying to display the list of all available reports

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/reports#115]
### Environment

- Platform version: 7.0
- Client type: Web
- Operating system: Windows

### Description of the bug or enhancement

1) Open **refapp**
2) **Application** -> **Cars**
3) Click on the **Print form action** button

**AR**: 
```
ClassCastException: com.haulmont.cuba.web.gui.components.WebTabWindow cannot be cast to com.haulmont.cuba.gui.screen.compatibility.LegacyFrame
```

**ER**: 
The list of all available reports

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[cb57f113](https://git.haulmont.com/platform/reports/commit/cb57f113ef0e39e5954dae21016cdc3367b9c08e) in **master** - ClassCastException occurred while trying to display the list of all available reports #115
