### ISSUE TITLE
Provide vaadin-themes artifact for Studio theme variables editor

### ISSUE THREAD

**Issue by Gasloff** [cuba-platform/reports#117]
In CUBA 6.10 we use project dependencies to resolve Vaadin and CUBA theme variables.
In CUBA 7 we don't have themes artifacts in the dependencies

**Comment by jreznot** [comment]
Issue moved to [cuba-platform/cuba-gradle-plugin #73](https://github.com/cuba-platform/cuba-gradle-plugin/issues/73) via [**ZenHub**](https://www.zenhub.com/)
