### ISSUE TITLE
Unfetched attribute when export report from entity inspector

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#125]
https://www.cuba-platform.com/discuss/t/cannot-get-unfetched-attribute-on-report-export/7193
### Environment

- Platform version: 6.10.0

### Description of the bug or enhancement
  - Open entity inspector
  - Select report entity type
  - Try to export report
### Actual behavior
```
Caused by: java.lang.IllegalStateException: Cannot get unfetched attribute [code] from detached object com.haulmont.reports.entity.ReportGroup-4e083530-0b9c-11e1-9b41-6bdaa41bff94 [detached]
```

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[d0f5a55c](https://git.haulmont.com/platform/reports/commit/d0f5a55cd16502d033ab94c78e26f816aa1b805d) in **release_6_10** - Unfetched attribute when export report from entity inspector #125

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[b2984efe](https://git.haulmont.com/platform/reports/commit/b2984efe1d08fe3e9481e31f406199160a84353d) in **master** - Unfetched attribute when export report from entity inspector #125
