### ISSUE TITLE
Update YARG dependency to 2.1

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#126]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement
cuba-platform/yarg#97

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[ab342d1b](https://git.haulmont.com/platform/reports/commit/ab342d1bbaf061f6ed18eafc505fd1f8bb916c64) in **master** - Update YARG dependency to 2.1 #126
