### ISSUE TITLE
DOCX reports are created but are not opened

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/reports#129]
### Environment

- Platform version: 7.0
- Client type: Web
- Operating system: Windows
- Only for Java 10

### Description of the bug or enhancement

1) Create DOCX report using wizard
2) Run the report
3) Try to open the report

AR:
LibreOffice tries to open the report some time, then closes

See the report:
[Report for entity User.zip](https://github.com/cuba-platform/reports/files/2624612/Report.for.entity.User.zip)
And the rezult file:
[Report for entity User (1).docx](https://github.com/cuba-platform/reports/files/2624616/Report.for.entity.User.1.docx)

**Comment by andreysubbotin** [comment]
LibreOffice error: https://www.mail-archive.com/libreoffice-bugs@lists.freedesktop.org/msg515559.html

**Comment by andreysubbotin** [comment]
Git changes: https://git.haulmont.com/platform/reports/commit/c4a25782d4e504b024eaf2a712f2ecda51983101

**Comment by sukhova** [comment]
On Java 7 it's okey now, but on Java 10 DOCX reports are created but are not opened

**Comment by andreysubbotin** [comment]
Sample?

**Comment by sukhova** [comment]
[docx to docx (1).docx](https://github.com/cuba-platform/reports/files/2639344/docx.to.docx.1.docx)
[docx to docx.zip](https://github.com/cuba-platform/reports/files/2639345/docx.to.docx.zip)
