### ISSUE TITLE
Add context help for output name pattern of Report Template

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#13]
Add button that will show context help with examples and usage description

---
Original issue: https://youtrack.haulmont.com/issue/PL-7843

**Comment by soraksh** [comment]
[9c011284](https://git.haulmont.com/platform/reports/commit/591963dacdd2b3e486b45cacaeecdc98334fc36f)

**Comment by soraksh** [comment]
Help button added to report wizard and template editor.

**Comment by natfirst** [comment]
Help button should look the same as the context help (see, for example, Group constraint editor). It should be black.
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/a9253465-d632-452a-85c1-9d21d8f20a3f)

The code in the text should have the code style. It should stand out from the other text.

**Comment by soraksh** [comment]
[05ac86d2](https://git.haulmont.com/platform/reports/commit/05ac86d20afe868cee284dbf367570952e4e7140)

**Comment by natfirst** [comment]
Add a  paragraph indents to the text, now it looks unreadable

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[a93882b3](https://git.haulmont.com/platform/reports/commit/a93882b314368ec35f82ec6193dbdca91d55b8c9) in **master** - Add context help for output name pattern of Report Template #13
