### ISSUE TITLE
Popup context help is not shown correctly in ReportWizard

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/reports#131]
### Environment

- Platform version: 7.0
- Operating system: Windows

### Description of the bug or enhancement
1) Open ReportWizard
2) Move mouse under *Report type* list

AR:
![104.JPG](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/de3ed41f-4f1c-4633-9f2c-ad256b94c8c8)

**Comment by glebfox** [comment]
The ability to define HTML description has been introduced in cuba-platform/cuba#1676

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[2e23b051](https://git.haulmont.com/platform/reports/commit/2e23b0519d287750817e5d08cdff75cc7b85a555) in **master** - Popup context help is not shown correctly in ReportWizard #131
