### ISSUE TITLE
ParameterEditor should use parametrized collections with ScreensHelper

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/reports#133]
### Environment

- Platform version: 7.0.0

### Description of the bug or enhancement

Relates to https://github.com/cuba-platform/cuba/issues/1629

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[ed26529f](https://git.haulmont.com/platform/reports/commit/ed26529f6a4c03faf4d4161b0776e290b3b8e82a) in **master** - ParameterEditor should use parametrized collections with ScreensHelper #133
