### ISSUE TITLE
Missing caption for Run button in Run Reports screen

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/reports#139]
### Environment

- Platform version: 7.0.0

### Description of the bug or enhancement

- Minimal reproducible example

1. Open Administration - Run Reports

- Actual behavior

![image](https://user-images.githubusercontent.com/1066152/50221509-c83acb80-03ae-11e9-9dea-272af650fc11.png)

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[ecbde4c5](https://git.haulmont.com/platform/reports/commit/ecbde4c50763540f37e3d839a9da3b216cfd311a) in **master** - Missing caption for Run button in Run Reports screen #139
