### ISSUE TITLE
REST API for Reporting add-on

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#14]
Add REST API for reporting module

Proposal for implementation:
1. method to get a list of reports
2. method to get Report Info (parameters, output file type and so on)
3. method to launch a report and get the result
4. method to return Swagger documentation

Implementation contains 3 methods:

1. GET /report with no arguments, it returns JSON array with a list of reports
2. GET /report/{id} with one string argument report id. 
It returns JSON object with information about the report: name, code, parameters with their types, list of contained templates.
3. POST /run/{id} with one string argument report id. Post body contains report parameters and template code
4. GET /docs/swagger.json documentation

Reports for REST API should have a special flag: Visible for REST API on Roles and Screens tab. Reports without this flag isn't visible for REST API

Tested locally on: http://localhost:8080/app/rest/reports/v1/

---
Original issue: https://youtrack.haulmont.com/issue/PL-8202

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[5fd7200f](https://git.haulmont.com/platform/reports/commit/5fd7200fbb767e0dda9e5d16f15fed5346021a09) in **release_6_10** - REST API for Reporting add-on #14

**Comment by andreysubbotin** [comment]
Git changesets by `subbotin`: 

[5fd7200f](https://git.haulmont.com/platform/reports/commit/8bc2cc8114b61e7fc55a2830c0b62e7ba743b856) in **master** - REST API for Reporting add-on #14

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[ab981636](https://git.haulmont.com/platform/reports/commit/ab98163651b57c89156be240511f17abdb3f1860) in **master** - REST API for Reporting add-on #14

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[c0e05e2d](https://git.haulmont.com/platform/reports/commit/c0e05e2d781a291d7e399de4bf6d40b4993ee8c5) in **release_6_10** - REST API for Reporting add-on #14

Swagger Docs

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[f40bb659](https://git.haulmont.com/platform/reports/commit/f40bb659db1d096e7083e599b016fb042a56168d) in **master** - REST API for Reporting add-on #14

Swagger Docs

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[f357fb83](https://git.haulmont.com/platform/reports/commit/f357fb835550ee2232aac800649bf4c9b7198502) in **master** - REST API for Reporting add-on #14

Swagger Docs (fix list)

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[92a4684c](https://git.haulmont.com/platform/reports/commit/92a4684cf139b02e7bfb6805afb51078b0b0e0ed) in **release_6_10** - REST API for Reporting add-on #14

Swagger Docs (fix list)

**Comment by andreysubbotin** [comment]
cuba-platform/refapp/issues/6

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[59c12117](https://git.haulmont.com/platform/reports/commit/59c12117a47f6bbb46857a54f3b5c91ae722b8f4) in **master** - REST API for Reporting add-on #14

Fix update scripts

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[1f51ff3e](https://git.haulmont.com/platform/reports/commit/1f51ff3e00999febad2bc24ae9d05020f1191d63) in **release_6_10** - REST API for Reporting add-on #14

Fix update scripts

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[c369810e](https://git.haulmont.com/platform/reports/commit/c369810e717167b5ec7654a6fd215a8efb85b3dc) in **release_6_10** - REST API for Reporting add-on #14

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[da123385](https://git.haulmont.com/platform/reports/commit/da1233850a4f21bcde6f9b065ee964ea7d0dfc4c) in **release_6_10** - REST API for Reporting add-on #14

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[31759f06](https://git.haulmont.com/platform/reports/commit/31759f062d338d311d4f4be5a426d764ff2a8f2e) in **master** - REST API for Reporting add-on #14

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[e606e670](https://git.haulmont.com/platform/reports/commit/e606e670bec4524a4686c199b057f2e6b8b4a1d0) in **master** - REST API for Reporting add-on #14

**Comment by sukhova** [comment]
1) Run report with empty body in POST query
2) Get uninformative response : {
    "error": "Server error",
    "details": ""
}

Logs:
`ERROR c.h.r.c.RestControllerExceptionHandler  - Exception in REST controller
org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void com.haulmont.reports.web.restapi.v1.ReportRestController.runReport(java.lang.String,java.lang.String,javax.servlet.http.HttpServletResponse)`

**Comment by sukhova** [comment]
1) Run a report without template
2) Get uninformative response : {
"error": "Server error",
"details": ""
}

Logs:
`ERROR c.h.r.c.RestControllerExceptionHandler  - Exception in REST controller
com.haulmont.reports.exception.ReportingException: No default template specified for report [Book availability in department (2)]`

**Comment by sukhova** [comment]
1) Create a report with "entity" parameter
2) Run this report with a non-existent ID of entity
3) Get uninformative response : {
"error": "Server error",
"details": ""
}

Logs:
`ERROR c.h.r.c.RestControllerExceptionHandler  - Exception in REST controller
java.lang.IllegalStateException: No results`

**Comment by sukhova** [comment]
1) Run a PDF\HTML\DOC report without installed OpenOffice\LibreOffice
2) Get uninformative response : {
"error": "Server error",
"details": ""
}

Logs:
`ERROR c.h.r.c.RestControllerExceptionHandler  - Exception in REST controller
com.haulmont.reports.exception.FailedToConnectToOpenOfficeException: Unable to create Open office components.`

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[4ac1e564](https://git.haulmont.com/platform/reports/commit/4ac1e56453a71240004a0622b241c39b6661457e) in **release_6_10** - REST API for Reporting add-on #14

Fix review

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[89df3a70](https://git.haulmont.com/platform/reports/commit/89df3a702922908c1cf2758f098e7fbff179dd00) in **master** - REST API for Reporting add-on #14

Fix review

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[33f1629d](https://git.haulmont.com/platform/reports/commit/33f1629d362b52d9b2dab0c31adff82b720c26a8) in **release_6_10** - REST API for Reporting add-on #14
Fix bugs

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[5606cf01](https://git.haulmont.com/platform/reports/commit/5606cf01443dabf3ba0bd28ebb1fabb3ba6aab52) in **master** - REST API for Reporting add-on #14
Fix bugs

**Comment by natfirst** [comment]
1. Create a project on 6.9.5 platform
2. Run the app, create a report
3. Upgrade the platform version to 6.10
4. Update the DB
```
org.gradle.api.GradleException: Exception when executing SQL: alter table REPORT_REPORT add REST_ACCESS boolean default false
java.sql.SQLSyntaxErrorException: ORA-00984: употребление столбца здесь недопустимо
```

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[06ad6602](https://git.haulmont.com/platform/reports/commit/06ad66029de087f012d96b31fbf8abd0d5c07044) in **master** - REST API for Reporting add-on #14
