### ISSUE TITLE
Permanent XSS attack through Report's Name field

### ISSUE THREAD

**Issue by bernatgs** [cuba-platform/reports#140]
### Environment

- Platform version: 6.9.10 

- Client type: Web
- Browser: tested in Firefox and Chrome

### Description of the bug or enhancement

- Login and navigate to _Reports > Reports_
- Click _Create > New_
- In the name field, type `<img src=x onerror="alert('persistent XSS attack')";>`
- Click _Save and close_
- Edit the newly created report by double-click or click & Edit
- Hover mouse over the tab with the text _Edit report "<img src=x o..._

![imagen](https://user-images.githubusercontent.com/5872879/50345763-702bd280-0530-11e9-8c3b-5e7265ed2738.png)

- Expected behavior: nothing happens
- Actual behavior: javascript code is executed

![imagen](https://user-images.githubusercontent.com/5872879/50345890-dc0e3b00-0530-11e9-9d4f-7c5422dcaea3.png)

**Comment by bernatgs** [comment]
This vulnerability was discovered by @juanrafaelvillen, please contact him for any question or comment.

**Comment by glebfox** [comment]
Fixed in cuba-platform/cuba#1741

**Comment by evgenypopov2** [comment]
Tell me please how can I block the vulnerability in 6.3.4 CUBA platform version? Unfortunately upgrade to 6.8-6.10 is not possible.

**Comment by jreznot** [comment]
Please use forum for discussions and questions. Answered here: https://www.cuba-platform.com/discuss/t/mitigate-xss-vulnerability-in-reports-version-6-3-4/8378
