### ISSUE TITLE
Params transformation improvement 

### ISSUE THREAD

**Issue by Quicksy** [cuba-platform/reports#148]
### Environment

- Platform version: 6.8.14

### Description of the bug or enhancement

CUBA have "Transformation" feature for report parameters. Currently, if parameter not marked as "required" and hasn't been filled in, transformation script just ignored, parameter remained "null' and we have to process it somehow in report bands. 
It would be very useful if transformation script still would be run on empty parameters to transform null to some particular value. 

For example:
We have some string parameter that later will be used in SQL script. If it is not filled, we want it to be set to "%". At the same time we can't set "%" as default value, because it will be displayed every run and may confuse customers. In this case it would be great if we just could transform null to "%" in background using transformation script.

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[590408dc](https://git.haulmont.com/platform/reports/commit/590408dc17f689812b3c17ea08811f539a13b211) in **release_6_10** - Params transformation improvement #148

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[829236b1](https://git.haulmont.com/platform/reports/commit/829236b1676157a151ea6232f3b46349431f9d71) in **release_6_8** - Params transformation improvement #148
