### ISSUE TITLE
Hide custom template configuration for chart templates

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#151]
https://www.cuba-platform.ru/discuss/t/custom-shablon-otcheta-opredelyaemyj-skriptom/2608

### Environment

- Platform version: 6.10

### Description of the bug or enhancement

- Minimal reproducible example
- Expected behavior
- Actual behavior

**Comment by haulmont-git** [comment]
Git changesets by `shchienko`: 

[e82d376a](https://git.haulmont.com/platform/reports/commit/e82d376a664c878d61011c62804666af0973d12d) in **release_6_10** - Hide custom template configuration for chart templates #151
