### ISSUE TITLE
Ability to add custom JSON for a chart report

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/reports#153]
### Description of the bug or enhancement

- Minimal reproducible example

1. Open Reports > Reports
2. Click Create > Using Wizard
3. Fill required fields, for `Template type` set *Chart*
4. Go to the chart setup step

- Expected behavior

There is a way to add custom settings for a char

- Actual behavior

There is no way to add custom settings for a chart

**Comment by pribavkindenis** [comment]
For QA:
* `com.haulmont.reports.entity.charts.AbstractChartDescription#customJsonConfig` represents the custom JSON configuration for a chart.
* `chart-edit-frame.xml` contains JSON editors ( `serialJsonConfigEditor` and `pieJsonConfigEditor` ) managed by `com.haulmont.reports.gui.template.edit.ChartEditFrame` controller.
* `com.haulmont.reports.gui.template.edit.JsonConfigValidator` is used to validate the custom JSON configuration for a chart.
* `com.haulmont.reports.entity.charts.ChartToJsonConverter#mergeJsonObjects` and `com.haulmont.reports.entity.charts.ChartToJsonConverter#mergeJsonArrays` are used to merge the default JSON diagram configuration with the custom one if provided.

**Comment by pribavkindenis** [comment]
Now in the report template chart editor, you can see the source code editor called "JSON configuration" which allows you to paste any [AmCharts](https://www.amcharts.com/docs/v3/reference/tag/javascript-charts/) JSON configuration for pie and serial charts. "JSON configuration" context helpers provide you example configurations for a pie and a serial chart respectively:

![pie.png](https://images.zenhubusercontent.com/5c0009819329c41b135e8fef/fd82b27c-b15a-4537-a9a5-8c66f1f410c5)

![serial.png](https://images.zenhubusercontent.com/5c0009819329c41b135e8fef/1378eade-ccb3-43d8-b6e1-7db754989825)

**Comment by glebfox** [comment]
@pribavkindenis could you please provide JSON snippets?

**Comment by pribavkindenis** [comment]
JSON configuration for a serial chart:
```json
{
    "theme": "dark",
    "backgroundAlpha": 1,
    "backgroundColor": "black",
    "startDuration": 1,
    "depth3D": 20,
    "angle": 30,
    "graphs": [{
        "fillAlphas": 1,
        "lineAlpha": 1,
        "fillColors": ["#f12711", "#f5af19"],
        "lineColor": "black",
        "balloonColor": "#f12711"
    }]
}
```

JSON configuration for a pie chart:
```json
{
    "theme": "dark",
    "backgroundAlpha": 1,
    "backgroundColor": "black",
    "depth3D": 20,
    "angle": 40,
    "colors": [
        "#0dffdc",
        "#00c6eb",
        "#0091ff",
        "#0c4ae8",
        "#1111fa"
    ]
}
```
