### ISSUE TITLE
Double-click attribute in the ReportWizard is not working

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/reports#155]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

1) Open the Report Wizard
2) On the **Select attributes for the simple report region** step select some attribute and double-click it

**ER**: attribute will be added to the list of selected attributes (6.10 is OK).

**Comment by knstvk** [comment]
TreeTable doesn't support double click?

**Comment by natfirst** [comment]
Already fixed in https://github.com/cuba-platform/cuba/issues/1531
