### ISSUE TITLE
Only default template displayed in Run report screen if report run from the report editor screen

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/reports#166]
#### Environment

- Platform version: 6.10.8

#### Description of the bug or enhancement

1. Create a simple report
2. Open Template tab and add one more template (for example, Table report)
3. Click `Save` and `Run`

A.R. Only default template will be available from the Run screen
If the report is saved and the editor is closed, then all templates will be displayed in Run report screen

**Comment by jreznot** [comment]
May be duplicates https://github.com/cuba-platform/reports/issues/53

**Comment by konyashkina** [comment]
Tested on
1.  CUBA Platform version: 7.3-SNAPSHOT
CUBA Studio plugin version: 15.4-202 

2. CUBA Platform version: 7.2-SNAPSHOT
CUBA Studio plugin version: 15.4-202

with IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

Verified.
