### ISSUE TITLE
Exception while downloading report template

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/reports#169]
### Environment

- Platform version: 7.0.2
- Operating system: macOS
- **JDK: 11**

### Description of the bug or enhancement

- Minimal reproducible example

. Create any XLSX report using **Report Wizard**
. Try to download report template from wizard screen

- Expected behavior

A template is downloaded

- Actual behavior

ClassNotFoundException: javax.xml.bind.JAXBException

**Comment by glebfox** [comment]
It appears that the issue can be reproduced if both Java **8** and **11** are installed and `JAVA_HOME` references on Java **11**. 

Environment details: 

**Java 11**
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```

**Java 8**
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```

**Comment by NikitaShchienko** [comment]
To solve this problem, you need to add to the build.gradle file:
```
configure(globalModule) {
    dependencies {
        if (!JavaVersion.current().isJava8()) {
            runtime('javax.xml.bind:jaxb-api:2.3.1')
            runtime('org.glassfish.jaxb:jaxb-runtime:2.3.1')
        }
    }
}
```
