### ISSUE TITLE
Unable to change Dataset type in the Report Wizard

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/reports#176]
### Environment

- Platform version: 7.0, 7.1

### Description of the bug or enhancement

1) Create a project with report addon or use demo refapp
2) Create a report via the wizard. 
3) Try to change Dataset type in the Report Editor

**AR**:
Nothing happens in the right panel![reportCreate.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/092a9626-16f2-4ed4-9b17-23f188c6f4db)

**Comment by NikitaShchienko** [comment]
Hello. 
The problem is not reproduced.
