### ISSUE TITLE
Store and show report execution history

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/reports#178]
### Description of the bug or enhancement
Take already existing feature from Sherlock.
1) Store execution history for every report:
- start, finish time, execution time
- Report name, code, ID (denormalized to keep data even after report is deleted)
- User who launched it
- Success
- Cancelled
- Parameters

2) Optional scheduler to clean old execution history.

![image](https://user-images.githubusercontent.com/6158807/56025134-91544100-5d22-11e9-825d-111688ae8052.png)

**Comment by aleksey-stukalov** [comment]
Let's move it to a separate tiny add-on. This is not about reporting really, this is about storing files.

**Comment by alexbudarov** [comment]
I still think it should be in core.
Because without having report execution history often you can't understand which user has overloaded your production server (right now or at some point in the past) with too bulky report.

**Comment by knstvk** [comment]
Reporting is already an add-on, so I vote for including all necessary stuff in it directly as long as it doesn't require additional dependencies.

**Comment by alexbudarov** [comment]
### Solution
Added Reports -> Reports -> Execution history screen:
![image](https://user-images.githubusercontent.com/6158807/61543898-6716cb80-aa55-11e9-9481-b80b0f989063.png)

The screen was not added to menu. It can be opened by pressing Execution history button in Reports browser.

If any report was selected in Reports table - then execution history is additionally filtered by selected report.
If no reports were selected in Reports table - all reports are shown.

Report name and code are denormalization fields, remembered at the time of execution.
"Cancelled" flag means that user launched report in the backround and then cancelled it.

Execution history is also recorded even for reports which are not yet saved to DB, but launched from Report Editor ("Run" button).

### Configuration
![image](https://user-images.githubusercontent.com/6158807/61544313-3d11d900-aa56-11e9-8a45-265c30b1f1f2.png)
All configuration properties are available in "Application properties" screen.
Execution history recording is disabled by default, turn on "reporting.executionHistory.enabled" property to enable it.

### Cleanup
You might want to set up execution history cleanup to delete old unnecessary data and prevent infinite table growing.
1) Create and activatescheduled task: 
Bean Name = reporting_ExecutionHistoryRecorder
Method Name = cleanupHistory()
Cron = nightly, e.g. "0 0 1 * * *"

2) Tune configuration properties.
- "reporting.executionHistory.cleanup.days", by default 2 years - delete all executions older than this number of days. If property = 0 then don't delete history by days.
- "reporting.executionHistory.cleanup.itemsPerReport", by default 1000 - leave no more than this number of history entries for every report. If property = 0 then don't delete history by items. This is useful for frequently run reports such as email templates, invoicing document templates etc.
