### ISSUE TITLE
XLSX Report fails when band has unlimited number of cols (e.g. band is defined as Sheet1!$1:$4)

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#18]
XLSX Report fails when band has unlimited number of cols (e.g. band is defined as Sheet1!$1:$4)

---
Original issue: https://youtrack.haulmont.com/issue/PL-8628

**Comment by NikitaShchienko** [comment]
Link to the commit: cuba-platform/yarg@c6d9e3b

**Comment by andreysubbotin** [comment]
FIxed in YARG 2.1.7
