### ISSUE TITLE
Scheduled reports

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/reports#181]
### Description of the bug or enhancement
This feature is implemented in Sherlock and can be taken from it with some changes / improvements.

Ability for a user to setup a schedule. Every day/week at specified time reports are run and sent by email to recipients.
For example: previous day / weekly statistics for managers.
Report parameters can be predefined constants or relative time variables like "today", "yesterday", "today - 5 days" etc.

![image](https://user-images.githubusercontent.com/6158807/56039763-11d86900-5d46-11e9-9cbe-0fc05b0030ff.png)

**Comment by aleksey-stukalov** [comment]
In fact, this feature can be easily implemented here https://github.com/cuba-platform/emailtemplate-addon. This addon composes e-mail along with attachments from CUBA reports - the only thing to be added is scheduling. I would vote for moving it from Reporting addon to Email Templates add-on.

**Comment by knstvk** [comment]
See also the [forum discussion](https://www.cuba-platform.com/discuss/t/has-anybody-built-a-user-interface-to-schedule-reports/8821).

**Comment by alexbudarov** [comment]
Some clarifications from my side:
- I am not asking to implement the feature right in the "reporting" addon.
- I am not asking to take feature as is from Sherlock. I've presented the screenshot just for inspiration to make description shorter.

**Comment by alexbudarov** [comment]
Solved by a community add-on: https://github.com/mariodavid/cuba-component-scheduled-reports
