### ISSUE TITLE
Update YARG version

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#182]
See cuba-platform/yarg#109

https://github.com/cuba-platform/reports-dependencies/network/alert/6.10.9/reports-core/pom.xml/org.apache.pdfbox:pdfbox/open
Reports 7.0, 7.1 -> YARG 2.1.5
Reports 6.10 -> YARG 2.0.19

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[f238b218](https://git.haulmont.com/platform/reports/commit/f238b218f3e4640c7e81195961dedbcaa5eb4277) in **release_6_10** - Update YARG version #182

**Comment by andreysubbotin** [comment]
For QA: reports smoke test and test HTML to PDF
