### ISSUE TITLE
Table report is printed with unknown column order

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#187]
Order of columns in he entity  browser:

![image](https://user-images.githubusercontent.com/17950251/66040325-390b3880-e528-11e9-8a3d-a40ceeeb9e25.png)

Order of fields in the Dataset in report:
![image](https://user-images.githubusercontent.com/17950251/66040342-40cadd00-e528-11e9-9055-154cdc0dd3f4.png)

And the report. The column order will be the same in the next report print but it does not repeat the order in the dataset.
![image](https://user-images.githubusercontent.com/17950251/66040351-46c0be00-e528-11e9-81df-42ff9b3c865a.png)

---
Original issue: https://youtrack.haulmont.com/issue/PL-9743

**Comment by NikitaShchienko** [comment]
We created a configurator for a report template of type Table.
On the left, you need to add the bands that you want to display, and on the right, rows are added with the key to the data and the name that will be displayed in the tables.

![image](https://user-images.githubusercontent.com/47520144/62307593-f16b2080-b494-11e9-9329-c089467d0a26.png)

Example:
[Report.zip](https://github.com/cuba-platform/reports/files/3457545/Report.zip)

**Comment by sukhova** [comment]
1) Open a **library** project
2) Create a **Report for list of entities, selected by query** for the _BookPublication_ entity
3) Set some simple query
4) See the band and query:
```
select
book_literatureType.name as "book.literatureType.name",
book.name as "book.name",
town.name as "town.name",
e.year as "year"
from library$BookPublication e  
left join e.book.literatureType book_literatureType 
left join e.book book 
left join e.town town 
 where e.year > ${year1}
```
5) Switch to the **Templates** tab
6) Open the Template editor:
![21](https://user-images.githubusercontent.com/40686909/70982520-8bdca100-20d0-11ea-8d0f-b64dd4ec6dfa.PNG)
7) Run the report:

**AR**:
![22](https://user-images.githubusercontent.com/40686909/70982596-b2024100-20d0-11ea-9a90-d40d3f474398.PNG)

8) Try to change the table template:
![23](https://user-images.githubusercontent.com/40686909/70982720-eaa21a80-20d0-11ea-86a2-3c1d2aa0f0e0.PNG)
9) Run the report:

**AR**:
![24](https://user-images.githubusercontent.com/40686909/70982777-04dbf880-20d1-11ea-805c-5bc017957e4b.PNG)

See the report:
[Report for entity _Publication_2.zip](https://github.com/cuba-platform/reports/files/3972451/Report.for.entity._Publication_2.zip)

**Comment by Mihail063** [comment]
1. Create a new entity 
2. Create an enum attribute for the created entity (for example Type)
3. Create a browser and editor screen
4. Run the project and create an entity instance
5. Start to create a new report for the entity 
6. Select the table template type and click Next
7. Select the added enum entity attribute and save the report
8. Run the created report for the added entity instance

AR: Enum type attribute value is not shown
![изображение](https://user-images.githubusercontent.com/24281695/73281912-2240ce00-420a-11ea-89d6-a520ebc7f387.png)
