### ISSUE TITLE
Increase template content column size on MySQL

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#196]
### Environment

- Platform version: 7.0
- Database: MySql

## Description of the bug or enhancement
Unable to save a report with a template whose size is greater than 64 KB in the Mysql database.
https://www.cuba-platform.com/discuss/t/report-template-truncation-error-with-mysql/9140

### Minimal reproducible example
1. Create a Cuba project with the Mysql database and add to project Addon Report
2. Run the project
3. Create any report or import [Report.zip](https://github.com/cuba-platform/reports/files/3385883/Report.zip)
4. Replace report template with a template larger than 64 kb ([Test Report.xlsx](https://github.com/cuba-platform/reports/files/3385884/Test.Report.xlsx))
5. Try to save

### Expected behavior: 
Report saved without errors
### Actual behavior: 
Failed to save the report

![image](https://user-images.githubusercontent.com/47520144/61122417-cc494a80-a4b2-11e9-87fc-922babd12aac.png)

**Comment by NikitaShchienko** [comment]
Added to 4348cbb
