### ISSUE TITLE
Create button on Reports browser lost its icon

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/reports#205]
### Environment

- Platform version: 6.10, master

### Description of the bug or enhancement
report-browse.xml:
```
<popupButton id="popupCreateBtn" icon="theme://actions.Create.icon" caption="mainMsg://actions.Create"/>
```
"actions.Create.icon" theme variable can not be found anywhere in refapp-all project.
So in running application there is no icon for Create popup button:
![image](https://user-images.githubusercontent.com/6158807/61706613-8feed780-ad59-11e9-86af-a9f5fe8a67d1.png)

**Comment by haulmont-git** [comment]
Git changesets by `shchienko`: 

[4d76279c](https://git.haulmont.com/platform/reports/commit/4d76279c8c91b177cf1fdbac6fbbaa7c55145362) in **release_6_10** - Create button on Reports browser lost its icon #205
