### ISSUE TITLE
Report generation error if html formatted param contains '&'

### ISSUE THREAD

**Issue by kandalin-d** [cuba-platform/reports#210]
### Environment

- Platform version: 5.9.SNAPSHOT

### Description of the bug or enhancement

- Import report
[docx_html_test_report.zip](https://github.com/cuba-platform/reports/files/3441641/docx_html_test_report.zip)

- Run report and see stacktrace in log. Error occured if ${html} formatted parameter contains '&' symbol with any word ('&TECHNOLOGY' for example)
- Expected behavior: Report is finished without error. Result 'docx' file can be opened in OpenOffice and MS Word with filled values.
- Actual behavior: Result value in report is missing when result 'docx' file is opened in OpenOffice. And when opening result 'docx' file in MS Word error appears.

**Comment by andreysubbotin** [comment]
`&` - reserved char in the HTML. Escape manually.
