### ISSUE TITLE
Html-editor hidden when output type pdf

### ISSUE THREAD

**Issue by NikitaShchienko** [cuba-platform/reports#217]
### Environment

- Platform version: 6.10
- Add-on version: 6.10

### Description of the bug or enhancement

Html-editor hidden when output type pdf.
#### Minimal reproducible example

Create a new report with an HTML template. Change the type of output template to PDF.

- Expected behavior
HTML-editor is not hidden
- Actual behavior
HTML-editor is hidden
![image](https://user-images.githubusercontent.com/47520144/63017533-a941fa00-bea7-11e9-8ac0-747bed91e000.png)

**Comment by haulmont-git** [comment]
Git changesets by `shchienko`: 

[c8b6953b](https://git.haulmont.com/platform/reports/commit/c8b6953b8ffc082fb046bdcdaf71dd8aa3e71ff2) in **release_6_10** - Html-editor hidden when output type pdf #217
