### ISSUE TITLE
Select "Entity" parameters by typing in parameter field (similar to filters)

### ISSUE THREAD

**Issue by PolinaSannikova** [cuba-platform/reports#222]
### Environment
- Platform version: 6.10.12

### Description of enhancement
Right now, when specifying input parameter of type 'Entity' in report, user needs to press '...' to open a separate screen to select the entity. This is inconvenient and annoying - each time user needs to open screen, maybe use some filter to find the entity, then select entity and press OK.

However, in many places parameter selection is realized a lot nicer (e.g. in filters) - user can start typing name of entity and system would fill in the rest if it finds a result (according to entity's NamePattern). User also can open a screen to select from a special lookup screen.

**Proposed improvement:**
Have "entity" parameter selection work in similar way:

1. User can select entity same way as now - by pressing on '...'
2. AND user can start typing entity name and press enter - dropdown list with matching results (according to NamePattern) is displayed

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[1e82808e](https://git.haulmont.com/platform/reports/commit/1e82808e7364443234a0f4baf20afef53d8bf9f6) in **release_6_10** -  Select "Entity" parameters by typing in parameter field (similar to filters) #222

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[aa00659b](https://git.haulmont.com/platform/reports/commit/aa00659bce76cc14d656af4e1433eaae0ebf1e15) in **release_6_10** - JPQL exception fix and suggesters for entity param lookup #222

**Comment by soraksh** [comment]
"Lookup" checkbox which enables lookup action added to parameter editor screen (visible if "Entity" type selected).

**Comment by gogosofta** [comment]
Hi,
is version 6.10.16 going to be released any soon?
