### ISSUE TITLE
Field value formats for LocalDate, LocalDateTime fields

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#230]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement
Field value formats only work for Date type and don't work for LocalDate, LocalDateTime types. 

https://www.cuba-platform.com/discuss/t/field-value-formats/10502

**Comment by Mihail063** [comment]
Value formats are applied by default only for Date and DateTime after report generation.
![изображение](https://user-images.githubusercontent.com/24281695/70982790-0dccca00-20d1-11ea-97bf-88e75de2a589.png)

**Comment by NikitaShchienko** [comment]
For the LocalTime and LocalDateTime data types, there is no need to generate a formatter, for them, the date format is taken from datatypes.
