### ISSUE TITLE
Field value formats do not work for the table template

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/reports#237]
### Description of the bug

- Minimal reproducible example

1. Create a new report with a table template 
2. Open the Parameters and Formats tab
3. Create a new value format for any entity attribute
4. Run the report

- Actual behavior
Value format not applied

**Comment by Mihail063** [comment]
Field value formats  still do not work for the table template if report type "Report for list of entities" or "Report for list of entities, selected by query" is set

**Comment by NikitaShchienko** [comment]
Can't reproduce
