### ISSUE TITLE
Role.type is shown empty for the report type "Report for list of entities, selected by query"

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/reports#246]
### Environment

- Platform version: 7.2

### Description of the bug or enhancement

1. Create any role
2. Start to create a new report for the Role entity
3. Select the report type "Report for list of entities, selected by query" and click Next
4. Select the Role.name and Role.type attribute and save the report
5. Run the report for the created role from the previous step

- Actual behavior
Role.type is shown as empty
![изображение](https://user-images.githubusercontent.com/24281695/73946629-a92f2e00-490f-11ea-8506-201466481f1d.png)

**Comment by NikitaShchienko** [comment]
Fixed in cuba-platform/reports#237

**Comment by NikitaShchienko** [comment]
In the given example, the RoleType field is empty, because the null value is stored in the database.

To correctly display this field, you must create a formatter:

![image.png](https://images.zenhubusercontent.com/5ca35dde58f2cc4a01cea0c9/6b7d7fc2-6846-40aa-8a7f-47cde8e7eb4e)
