### ISSUE TITLE
system-reports-minimal role doesn't provide access to the root report menu

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/reports#252]
### Environment

- Platform version: 7.2.0

### Description of the bug or enhancement

The `system-reports-minimal` role doesn't provide access to the root **Report** menu as a result allowed screens can't be opened.

- Minimal reproducible example

0. Enable **Reports** add-on
1. Create a new user
2. Assign `system-minimal` and `system-reports-minimal`
3. Log in as a new user

- Expected behavior

Limited Reports menu is visible

- Actual behavior

No Reports menu

**Comment by andreysubbotin** [comment]
Not bug. Report menu is hidden by design.
