### ISSUE TITLE
Empty options for template selection in report editor

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/reports#255]
# Environment

- Platform version: 7.2.1

### Description of the bug or enhancement

- Minimal reproducible example
1) Create a report with several templates
![image](https://user-images.githubusercontent.com/19840141/77826985-772a9300-712c-11ea-8426-5e244bdb74a7.png)
2) Save it
3) In the report editor press Run
4) Expand the template selection dropdown
- Actual behavior 
The options list is empty.  The default is displayed. But if to deselect it, it disappears.
![image](https://user-images.githubusercontent.com/19840141/77827073-09cb3200-712d-11ea-82ca-7ef68f5da732.png)

**Comment by andreysubbotin** [comment]
@IskandarovRost perhaps it's a duplicate issue.

**Comment by Desire456** [comment]
Duplicates https://github.com/cuba-platform/reports/issues/166
