### ISSUE TITLE
Cannot assign RunReportAction to the button in XML

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/reports#259]
- Platform version: 7.2.4 

- Minimal reproducible example
Create an application and add reports. Then add the RunReportAction to the screen 
```
<action id="runReport" type="runReport"/>
```
And assign it to a button. 

- Expected behavior
When you click on button, Run Report window appears.

- Actual behavior
Nothing happens. But when we assign this action to a button manually:
```
@Subscribe
public void onInit(InitEvent event) {
    ownersTableRunReportBtn.setAction(new RunReportAction());
}
```
Then it works.

**Comment by andreysubbotin** [comment]
Can't reproduced.

**Comment by maistrenkoIulia** [comment]
can`t reproduce on 7.2.4; 7.2.6; 7.2-snapshot; 7.3-snapshot
