### ISSUE TITLE
Reports REST API improvements

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#260]
https://www.cuba-platform.com/discuss/t/include-report-group-as-part-of-report-information-rest-api/12201

### Environment

- Platform version: 7.2

### Description of the bug or enhancement
- Include information about a report group for report list and report by id requests.
- Include default parameter values for report input parameters.

### Implementation:
- Added `group` field to report. 
<details>
  <summary>Example</summary> 

  ```
  Request: /rest/reports/v1/report
  Responce:
  {
      "id": "eb7ac2aa-5cf9-c43a-eee8-eb2b33104297",
      "name": "Some Test Report",
      "code": "REP_T_1",
      "group": "4e083530-0b9c-11e1-9b41-6bdaa41bff94"
  }, {
      "id": "3e638c2b-9c10-368f-ac7c-a362e611d740",
      "name": "Report for entity \"Model\"",
      "code": "MODEL_TESTT",
      "group": "867d107e-05dc-1580-f8e2-f792247ca5e0"
  }
  ```
</details>

- Added `defaultValue` field to input parameter.
<details>
  <summary>Example</summary> 

  ```
  Request: /rest/reports/v1/report/3e638c2b-9c10-368f-ac7c-a362e611d740
  Responce:
  {
      "id": "3e638c2b-9c10-368f-ac7c-a362e611d740",
      "name": "Report for entity \"Model\"",
      "code": "MODEL_TESTT",
      "group": "867d107e-05dc-1580-f8e2-f792247ca5e0",
      "templates": [{
              "code": "DEFAULT",
              "outputType": "CHART"
          }
      ],
      "inputParameters": [{
              "name": "Needed",
              "alias": "needed",
              "type": "NUMERIC",
              "required": true,
              "hidden": false,
              "defaultValue": "3"
          }
      ]
  }
  ```
</details>

- added endpoint `/rest/reports/v1/group/{groupId}` to get group details
<details>
  <summary>Example</summary> 

  ```
  Request: /rest/reports/v1/group/867d107e-05dc-1580-f8e2-f792247ca5e0"
  Responce: 
  {
      "id": "867d107e-05dc-1580-f8e2-f792247ca5e0",
      "title": "Second",
      "code": "SECOND"
  }
  ```
</details>

**Comment by chavu** [comment]
Thank you for this but what would also be useful are the following
1. Ability to get list of reports for a given group code(alias not uuid)
2. ability to get a list of all groups available.
