### ISSUE TITLE
Wizard first step layout has an incorrect view in Helium theme

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/reports#266]
### Environment
- Platform version: 7.2
- Client type: Web
### Description of the bug or enhancement
- Minimal reproducible example
1) Add reports add-on
2) Add helium theme to the project
3) Open _Reports -> create -> Using wizard_ 
- Actual behavior
![image](https://user-images.githubusercontent.com/22093943/92116870-74337d00-ee05-11ea-806b-d6e05f833581.png)

**Comment by andreysubbotin** [comment]
Changeset made after release 7.2.9 build
