### ISSUE TITLE
Report regions table in Wizard second step has an incorrect view 

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/reports#270]
### Environment

- Platform version: 7.2 - SNAPSHOT

### Description of the bug or enhancement
1. Add reports addon to project
2. Open Reports table - Create report using wizard
3. Select some entity (e.g. User), report type, click Next
4. Select some entity attributes, click Ok
 
- Expected behavior
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/0843367f-36eb-4e7b-830a-749ff3256747)
- Actual behavior
Report regions table is not displayed
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/45372e94-7458-47b9-b98d-4e728b18c9a6)
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/46decab9-557d-460e-99ab-d01a60588545)

**Comment by andreysubbotin** [comment]
Caused by cuba-platform/reports#266
