### ISSUE TITLE
The list of reports is empty when trying to run report from entity screens

### ISSUE THREAD

**Issue by lovtsovaik** [cuba-platform/reports#271]
### Environment

- Platform version: 7.2.4, 7.2.9
- Documentation: https://doc.cuba-platform.com/reporting-7.2/wizard.html

### Description of the bug or enhancement
1. Setup the project as described in https://doc.cuba-platform.com/reporting-7.2/project_setup_report.html  
    - Clone and open project https://github.com/cuba-platform/sample-library-cuba7
    - Optional: update CUBA version (CUBA-Project properties - set Platform version = '7.2.9')
    - Add the Reporting addon if not active
    - Create the database on the local HyperSQL server: go CUBA → Create database in the main menu
    - Run the application
    - Open the server link and log in with username and password admin / admin

2. Define a new RunReportAction standard action and a button for it in the librarydepartment-browse.xml screen descriptor:
```xml
<action id="run" type="runReport"/>
```
```xml
<button id="runReportBtn" action="libraryDepartmentsTable.run"/>
```

3. Create report using wizard  
    parameters: Entity = library$BookInstance, Template type = XSLX, Report type = Report for List of entities
    attributes: BookItem.Publication.Book.Name, BookItem.LibraryDepartment.Name

4. Link report to screen  
    - Go to Roles and Screens tab in edit report screen
    - Add the library$BookPublication.browse screen from the dropdown list to the table below
    - Click Save and close

5. Optional: repeat 3-4 steps with other types of reports: Report for single entity; Report for List of entities, selected by query, as described in https://doc.cuba-platform.com/reporting-7.2/single_entity_report.html and https://doc.cuba-platform.com/reporting-7.2/query_report.html (without adding buttons)

6. Go to Reference - Departments screen

7. Click Run Report button

###### ER
The table in the modal window contains all added reports
see Figure 23. Run report in https://doc.cuba-platform.com/reporting-7.2/query_report.html 

###### AR
The table contains no reports

![reports empty list.PNG](https://images.zenhubusercontent.com/5f928f98512e55007e6435dc/29df3bee-cff0-4e92-a78a-c5137c9e7b96)

###### Comment
1. Report generation works correctly in the case of complete follow the instructions described in 
https://doc.cuba-platform.com/reporting-7.2/single_entity_report.html and https://doc.cuba-platform.com/reporting-7.2/list_of_entities_report.html 

2. Type of button (runReportBtn or listBtn) does not affect reports availability.
![no reports by single button.PNG](https://images.zenhubusercontent.com/5f928f98512e55007e6435dc/a1b2a49e-e1e7-42c1-99dd-267b38606509)

**Comment by andreysubbotin** [comment]
Caused by:  #232. Revert filtering by entity type for RunReport action
