### ISSUE TITLE
Update YARG to 2.2.8

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#273]
### Description of the bug or enhancement
https://github.com/cuba-platform/yarg/releases/tag/2.2.7

- Minimal reproducible example
Test DOC template and DOCX->PDF conversation

**Comment by maistrenkoIulia** [comment]
```
An error occurred while generating doc report. All attempts failed. Template name [Template for report _Report for entity _User__.doc] Report name [test]
Unable to create Open office components.
com.sun.star.comp.helper.BootstrapException: no office executable found!
no office executable found!
```
[test-report.zip](https://github.com/cuba-platform/reports/files/5510727/test-report.zip)
[report error.txt](https://github.com/cuba-platform/reports/files/5510728/report.error.txt)
