### ISSUE TITLE
Error with opening generated report file via Word Office 365

### ISSUE THREAD

**Issue by owlet1997** [cuba-platform/reports#288]
based on [forum's question](https://forum.cuba-platform.com/t/latest-ms-word-office-365-causing-error-when-used-to-create-docx-report-template-file/15289/8) 

### Environment

- Platform version: 7.2.13
- Web Word from Office 365
- OpenOfiice v.4.1.9

### Description of the bug or enhancement

- Minimal reproducible example

1. Create new project -> add Reports add-on
2. Run app -> Open Reports browser
3. Create new report using wizard fo User entity -> Finish 
4. Download generated template -> open the file -> copy content
5. Open [Web Word from Office 365](https://www.office.com/launch/word?auth=2) -> create new document  
6. Paste copied content ->Save -> Download to your PC
7. Upload created copy to report -> Save 
8. Run report -> Open with OpenOffice or smth else

- Expected behavior
Report is opened without any problems

- Actual behavior
![image](https://user-images.githubusercontent.com/45730069/122173129-806b6100-ce92-11eb-9ec6-45502ae3bf13.png)

Notes:
after fixing needs to be checked on desktop Word from Office 365

**Comment by Desire456** [comment]
For QA: need to use yarg 2.2-SNAPHOT version

**Comment by owlet1997** [comment]
problems with opening file via Open Office, v.4.1.9
