### ISSUE TITLE
HTML content is not displayed in generated report using HTML format

### ISSUE THREAD

**Issue by owlet1997** [cuba-platform/reports#291]
### Environment

CUBA Platform version: 7.2.13
CUBA Studio plugin version: 15.4-202
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
YARG v.2.2-SNAPSHOT

### Description of the bug or enhancement

**TC:**
1. Open attached project -> update db -> run
2. Login as admin -> Open new entity browser
3. Create new one -> set quite complicated formatted string to long string field:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/c8e9e187-d398-40e9-8667-154c66229531)
4. Open Reports -> Reports -> Import attached report
5. Run this report - > choose created entity

- Actual behavior
HTML content isn't displayed:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/b1808e20-6b3f-404c-a8d5-ffeebd5fdbb9)

- Expected behavior
All fields are displayed in generated report

[project](https://github.com/cuba-platform/yarg/files/6573893/helll.zip)
[report](https://github.com/cuba-platform/yarg/files/6800525/Report.for.entity._New.entity_.2.zip)

**Comment by Desire456** [comment]
Will fixed at https://github.com/cuba-platform/yarg/issues/152
