### ISSUE TITLE
Update reportException messages (OpenOffice -> LibreOffice)

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#30]
reportException.failedConnectToOffice=Couldn't find OpenOffice instance
reportException.noOpenOfficeFreePorts=Couldn't connect to OpenOffice instance. No free ports available.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9607

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[668326ac](https://git.haulmont.com/platform/reports/commit/668326acd05752cff97a0102e24c2d8be3100518) in **release_6_10** - Update reportException messages (OpenOffice -> LibreOffice) #30

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[dc5ecae1](https://git.haulmont.com/platform/reports/commit/dc5ecae108527976b14e5ee9a7cece10e85fcabb) in **master** - Update reportException messages (OpenOffice -> LibreOffice) #30

**Comment by natfirst** [comment]
Please, fix the text in the following code:
```
 throw new OpenOfficeException("Failed to connect to LibreOffice. Please check open office path " 
```

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[e23dc1d8](https://git.haulmont.com/platform/reports/commit/e23dc1d8be204e91a5690a29021b7644ef36b759) in **release_6_10** - Update reportException messages (OpenOffice -> LibreOffice) #30
