### ISSUE TITLE
Simplify crosstab creation

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#41]
Add new type of Report Band - Crosstab.

When user creates such band, system automatically creates 4 data sets for the band - StaticHeader, DynamicHeader, Master, Details, user can not remove them.
The Details query should have ability to refer to Main query results (example: id = ${Master.user_id})

On data load system automatically expand the data sets to bands. The bands should have the same names (StaticHeader , DynamicHeader, Master, Details). The bands should be organized to parent -> child structure. StaticHeader -> DynamicHeader, Master-> Details. Parents must be Horizontal, children must be Vertical.

The XLSX file should have the same named ranges on it.

Additionally, if  user provides *header_id* in DynamicHeader and in Details data sets, system checks if the certain Details query selects enough data and fill the missing data. In this case system also sorts Details results to match the DynamicHeader order. If *header_id* is not provided - system generates the report as is.

:link: Related links: {"relates to:": "https://youtrack.haulmont.com/issue/PL-10478"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-9865

**Comment by andreysubbotin** [comment]
Has already released on 6.8
