### ISSUE TITLE
Date from JSON is not printed when formatter is specified for the corresponding field 

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#43]
1) In a project enable Reporting addon
2) Create some entity with date, datetime and time properties
3) Start the application and create several instances of the entity
4) Using REST API get Json with the list of entities
5) Using wizard create a report "for the list of entity" and select all the date attribs
 !image.png!
6) change type of the dataset from list if entities to Json and specify the JSON with the list of entity instances
 !image2.png!
7) launch the report. Check how the dates are written to the output document

AR : Dates from JSON are not printed when formatters are specified for date fields.
 !image3.png!

 !image4.png!

---
Original issue: https://youtrack.haulmont.com/issue/PL-9913

**Comment by NikitaShchienko** [comment]
In the formatter editor, you can now create your own formatters using groovy.

![image](https://user-images.githubusercontent.com/47520144/59287429-b281d100-8c82-11e9-86e4-1af66f406de9.png)

The formatter gets the value through the variable "value", then convert the value to the desired format and return the new value.

**Comment by sukhova** [comment]
1) Open the formatter dialog for some attribute
2) Check the **Groovy script** checkbox
3) Copy this script:
```
import java.text.SimpleDateFormat

def simpleOldDateFormat = new SimpleDateFormat('yyyy-MM-dd HH:mm')

def simpleNewDateFormat = new SimpleDateFormat('dd/MM/yyyy HH:mm')

def oldDate = simpleOldDateFormat.parse(value)

return simpleNewDateFormat.format(oldDate)
```
4) Uncheck the **Groovy script** checkbox

![formatter](https://user-images.githubusercontent.com/40686909/60419164-ae97fd80-9bf5-11e9-84d9-96f6a8187e49.gif)

**AR**:
Groovy script is copied to the field **Format string**

**ER**:
When the user uncheck the **Groovy script** checkbox, the **Format string** field should become empty.

**Comment by sukhova** [comment]
1) Open the formatter dialog for some attribute
2) Check the **Groovy script** checkbox
3) Copy this script:
```
import java.text.SimpleDateFormat

def simpleOldDateFormat = new SimpleDateFormat('yyyy-MM-dd HH:mm')

def simpleNewDateFormat = new SimpleDateFormat('dd/MM/yyyy HH:mm')

def oldDate = simpleOldDateFormat.parse(value)

return simpleNewDateFormat.format(oldDate)
```

**AR**:
![60](https://user-images.githubusercontent.com/40686909/60420516-02f0ac80-9bf9-11e9-92ef-1d8ad42ad76e.PNG)

**ER**:
1) The dialog should be a little wider: 
in the **Groovy script** field the line `def simpleOldDateFormat = new SimpleDateFormat('yyyy-MM-dd HH:mm')` should be completely placed.

2) The **Full screen** link should be added to the top of the **Groovy script** field

**Comment by sukhova** [comment]
1) Create the formatter for some attribute
2) Check the **Groovy script** checkbox
3) Copy this script:
```
import java.text.SimpleDateFormat

def simpleOldDateFormat = new SimpleDateFormat('yyyy-MM-dd HH:mm')

def simpleNewDateFormat = new SimpleDateFormat('dd/MM/yyyy HH:mm')

def oldDate = simpleOldDateFormat.parse(value)

return simpleNewDateFormat.format(oldDate)
```
4) Click **OK**
5) Open the formatter dialog again
6) Uncheck the **Groovy script** checkbox
7) Open the **Format string** list

**AR**:
Groovy script was saved in the **Format string** list and it has become a very big

**ER**:
Groovy script should not be written to the list

![reportDate](https://user-images.githubusercontent.com/40686909/60591694-0b3f1800-9db0-11e9-95ea-9b467be1470e.gif)
