### ISSUE TITLE
Warn a user when output type is changed to "table"

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#44]
1) Create some great report with HTML template for instance or with some another hardly created template

!image.png!

2) Open the template editor and change Output type = Table/ Save the  template

!image3.png!

3) Reopen the template editor

AR: the great hardly created template file is lost. It seems some warning or confirmation dialog should be shown there.
!image4.png!

---
Original issue: https://youtrack.haulmont.com/issue/PL-9914

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[0fa44f10](https://git.haulmont.com/platform/reports/commit/0fa44f10b316020c0b9a26d487be0137c306a528) in **master** - Warn a user when output type is changed to "table" #44

**Comment by natfirst** [comment]
Fix the Russian warning, text should be "Текст шаблона будет удален при сохранении" or "Текст шаблона будет удален после сохранения"

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[5fefd011](https://git.haulmont.com/platform/reports/commit/5fefd0115d39bef37dc1a746c0ffaefa98a50812) in **release_6_10** - Warn a user when output type is changed to "table" #44

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[c600f814](https://git.haulmont.com/platform/reports/commit/c600f814cba08c18424917898f40045bd43b2ac6) in **master** - Warn a user when output type is changed to "table" #44
