### ISSUE TITLE
Add an ability to choose report template in the report editor screen

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#53]
Check a topic on the support forum: https://www.cuba-platform.com/discuss/t/no-option-to-choose-template-while-running-report-from-report-creation-edit-wizard/3372.

Report editor:
![image2](https://user-images.githubusercontent.com/1066152/54107375-60ff4700-43f2-11e9-9110-6f66c6a90bf0.png)

"Run reports" screen
![image](https://user-images.githubusercontent.com/1066152/54107378-6361a100-43f2-11e9-9f2e-613ee44af338.png)

**Comment by andreysubbotin** [comment]
Fixed

**Comment by IskandarovRost** [comment]
Reopen 
1) create several templates for a report
2) open the report editor
3) press the Run button
4) see the templates dropdown

AR: Only the default template is available
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/86542952-4852-4d59-af83-8bc2a5a08214)

**Comment by Desire456** [comment]
Duplicates #166
