### ISSUE TITLE
Html link does not work in report

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#60]
Steps to reproduce:
1. Create report, output parameter.
2. Create value formatter for output parameter with ${html} format string.
3. Return parameter with html code with link: <a href="..".> description</a>

Actual result:
pdf report just shows full text with <a href> inside.
docx report is crashing while opening.
 

---
Original issue: https://youtrack.haulmont.com/issue/PL-10503

**Comment by NikitaShchienko** [comment]
Hello. Checked a problem on version 7.0 and on 6.10. The problem did not reproduce.
