### ISSUE TITLE
Excessive WARN logging while generation DOCX / XLSX reports

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#62]
1. Check out related ticket
1. DOCX - it seems that it fails while loading fonts that are used in a report template
1. XLSX - it seems that document that is transforming with XSLT doesn't match to the `mc-preprocessor.xslt` file

---
Original issue: https://youtrack.haulmont.com/issue/PL-10640

**Comment by andreysubbotin** [comment]
Issue moved to [cuba-platform/cuba-gradle-plugin #47](https://github.com/cuba-platform/cuba-gradle-plugin/issues/47) via [**ZenHub**](https://www.zenhub.com/)
