### ISSUE TITLE
Jar Hell with "stax-api"

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#63]
jasperreports depends on castor-xml which in turn depends on two libraries with the same name:
```
+--- org.codehaus.castor:castor-xml:1.3.3
 |    +--- stax:stax:1.2.0
 |    |    \--- stax:stax-api:1.0.1
 |    \--- javax.xml.stream:stax-api:1.0-2
```

This leads to removal of dependency `stax-api:1.0-2` from Tomcat

:link: Related links: {"relates to:": "https://youtrack.haulmont.com/issue/PL-10646"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-10647

**Comment by andreysubbotin** [comment]
Fixed in cuba-platform/reports#126
