### ISSUE TITLE
Implement the ability to save/download the Pivot report results

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/reports#71]
Following "Implement ability to use "Pivot" table in the Reporting addon (as a chart)" #50 comment №15

### Environment
- Platform version: 6.9.SNAPSHOT

### Description
Usability: implement the ability to save/download the report results, both from "Show Pivot tables" screen and the report editor
![image](https://user-images.githubusercontent.com/11287637/39747678-024eb08a-52bf-11e8-95cf-4f698708be70.png)

**Comment by jreznot** [comment]
Pivot data can be exported since 6.10:

https://doc.cuba-platform.com/charts-6.10/pivotTable_extension.html

**Comment by andreysubbotin** [comment]
Related issue: https://github.com/cuba-platform/charts/issues/77
