### ISSUE TITLE
Show variables from the selected band in Pivot template editor

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/reports#72]
Following "Implement ability to use "Pivot" table in the Reporting addon (as a chart)" #50 comment №13

### Environment
- Platform version: 6.9.SNAPSHOT

### Description
Usability: show available variables from the selected band, i.e.:
- pre-process the report structure in the template editor, 
- receive the list of available variables and aliases 
- and use them as suggestions in the Name field of report properties editor

![image](https://user-images.githubusercontent.com/11287637/39747759-486f32d8-52bf-11e8-8192-0dc522701082.png)

**Comment by andreysubbotin** [comment]
Band variables are defined during report execution, so there is no way to determine variable names at configuration time.
