### ISSUE TITLE
Support Java 9 and 10 for Reporting

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#80]
Dependent issue: https://github.com/cuba-platform/cuba/issues/910

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[da31cf52](https://git.haulmont.com/platform/reports/commit/da31cf52d15ecf0faf688484d77c22a269f8114b) in **master** - Support Java 9 and 10 for Reporting #80

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[2b3672e8](https://git.haulmont.com/platform/reports/commit/2b3672e8b3cbb98a73df8058e1b66e0751098d7a) in **master** - Support Java 9 and 10 for Reporting #80
