### ISSUE TITLE
Ability to hide internal system reports from "Run reports" screen and report actions

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/reports#83]
### Description of the bug or enhancement
Reports are usually divided into two categories:

1. Which are meant to be launched manually from "Run reports" screen or by invoking one of Report actions.
2. Internal reports, used to create documents or PDF/XLS export etc. They are launched programmatically. They are **not** supposed to be launched manually by users. These reports can literally fail with exception when launched from UI, e.g. they expect some special input parameters.

Currently there is a way to hide a report from "run reports" UI by specifying at least one Role on Roles & Screens tab.

But this solution has drawbacks:
- Exporting/importing a report can change report roles if target server does not have the same roles as source server
- Administrator roles still can see all reports. System reports are not intended to be run from UI by anyone, even by administrators.

Sometimes we have organizational issues like: our QA create bugs "Report XXX doesn't work" when they are testing the system with administrator user account.

So the suggestion is to add ability to mark any report (or maybe report group) as internal. Internal reports are hidden from Run Reports screen and report actions for all users. Such report will be accessible only from Report browser which is considered as administrative UI.

**Comment by haulmont-git** [comment]
Git changesets by `adiatullin`: 

[733b411c](https://git.haulmont.com/platform/reports/commit/733b411c22cd9c182d7d669559789438b6f772f9) in **master** - Ability to hide internal system reports from "Run reports" screen and report actions (ref #83)
