### ISSUE TITLE
Get rid of Instance.getInstanceName() method

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/reports#87]

**Comment by jreznot** [comment]
Relates to https://github.com/cuba-platform/cuba/issues/891

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[fa2361be](https://git.haulmont.com/platform/reports/commit/fa2361be0ec1b0e0b69ac1b2b82a2e4c8617a75c) in **master** - Get rid of Instance.getInstanceName() method #87
