### ISSUE TITLE
ReportEditor: Several UI components don't take into account read-only role

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/reports#91]
### Environment

- Platform version: 6.9.3, 6.8.0

### Description of the bug

**Test Case:**
1. Login as a user with read-only role
2. Try to View an existing report

**AR:**

The following UI components are available to use:

![clip2net_180721140444](https://user-images.githubusercontent.com/6077149/43034537-32e2c35c-8cef-11e8-99b3-fd5088972be9.png)

![clip2net_180721140533](https://user-images.githubusercontent.com/6077149/43034536-32c39f40-8cef-11e8-9b9f-e272fccdc1b2.png)

Moreover, the edited report can be successfully saved.

**Comment by soraksh** [comment]
Also these UI components should not be available
![1](https://user-images.githubusercontent.com/23614267/47496062-dd8bf180-d866-11e8-8b1e-2b8e3ccd48c4.png)
![2](https://user-images.githubusercontent.com/23614267/47496077-e4b2ff80-d866-11e8-81d9-4b2f91b27527.png)

**Comment by soraksh** [comment]
![3](https://user-images.githubusercontent.com/23614267/47501473-a9b8c800-d876-11e8-8828-48d3743c6d54.png)
