### ISSUE TITLE
Make series reorderable in the chart template properties 

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#92]
### Environment

- Platform version: 6.9
- Client type: Web

### Description of the bug or enhancement
https://www.cuba-platform.ru/discuss/t/vozmozhnost-redaktirovaniya-poryadka-ryadov-dannyh-v-otobrazhenii-otcheta-diagrammy/1800

**Comment by haulmont-git** [comment]
Git changesets by `adiatullin`: 

[27f40ae7](https://git.haulmont.com/platform/reports/commit/27f40ae7235c1858b74b9f5a82620c9e1a74f3f3) in **release_6_10** - Make series reorderable in the chart template properties #92

**Comment by haulmont-git** [comment]
Git changesets by `adiatullin`: 

[cd55489a](https://git.haulmont.com/platform/reports/commit/cd55489a5d2ba02700e7d656074524ebc08a006b) in **master** - Make series reorderable in the chart template properties #92
