### ISSUE TITLE
Scroll box disappears in the report editor screen

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/reports#95]
Related issue: cuba-platform/cuba#1153

#### Environment

- Platform version: 6.9, 6.10, 7.0

#### Description of the bug or enhancement
1. Create a simple report with the CSV type
2. Open the report template for edit
3. Change the report type to the Chart
4. Select Serial chart
5. Set the Band type

**A.R.** The scroll box disappear from the screen, Save and Cancel buttons are not available

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/17b4981f-34e2-4cd8-ac80-0312f00a4dbd)

**Comment by Flaurite** [comment]
It is bug of vaadin

**Comment by natfirst** [comment]
Another case: https://www.cuba-platform.com/discuss/t/report-parameter-screen-scrollbar-disappears/6219/3

Steps to reproduce:
1. Create a new Report (no new bands or data or anything, we are just going to create the parameter screen)
2. Create 10 parameters (named p1 - p10, all of them take a “List of entities” such as User).
3. Create an 11th parameter (named p11, parameter type: date).
4. Run the report to display the parameter screen (scrollbar appears on right as there are a lot of parameters)
5. Scroll to bottom and set the value to p11 using the date picker.
6. Scrollbar disappears, need to hit refresh in the browser to get the scrollbar back.

I’ve seen the scrollbar disappear after setting a parameter of type “List of entities” as well but not consistently.

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/42922ecc-1c43-4e22-9dc5-ea853787e1bd)

Scrollbar has disappeared, can’t run the report or see other parameters.

**Comment by Flaurite** [comment]
Can't reproduce in 7.0
