### ISSUE TITLE
Incorrect images resize with ${imageFileId:WxH} in DOCX

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/reports#99]
Platform version: 6.9.5
[Forum issue](https://www.cuba-platform.ru/discuss/t/razmer-izobrazheniya-v-otchete-ne-sootvetstvuet-zadannomu-formatu/2011/5)

WTR
1. Import and deploy the `demo` project attached
1. Extract `filestorage` and put it in `demo\deploy\tomcat\work\app-core` (default work directory)
1. Run the app
1. Import `Reports.zip`
1. Run the reports 

ER:
Images in reports are resized to the format defined by `${imageFileId:WxH}` keeping the initial images' proportions.
For example:
Initial: 1024x768
Value format: 300x200
Result: 266x200

AR:
Some images are resized correctly, but initially big and initially small images become too small or too big, see the reports PDF results: [Report for single entity _Something_.pdf](https://github.com/cuba-platform/reports/files/2314072/Report.for.single.entity._Something_.pdf)

In the PDF  report attached, image format is set to 300x200.
The Name column displays the initial dimensions of images, the result of the resize is in the Image.ID column.

![screenshot_1](https://user-images.githubusercontent.com/11287637/44521036-c9027000-a6e2-11e8-93ca-8a1e8eb90094.png)

[demo.zip](https://github.com/cuba-platform/reports/files/2313912/demo.zip)

[filestorage.zip](https://github.com/cuba-platform/reports/files/2313911/filestorage.zip)

[Reports.zip](https://github.com/cuba-platform/reports/files/2313914/Reports.zip)

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[54653b01](https://git.haulmont.com/platform/reports/commit/54653b012548522310fc8ad363ac0c5f3abce482) in **release_6_10** - Incorrect images resize with ${imageFileId:WxH} in DOCX #99

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[8234f192](https://git.haulmont.com/platform/reports/commit/8234f192a5a537bc23bb055a4a98ee8ed7e31f51) in **release_6_9** - Incorrect images resize with ${imageFileId:WxH} in DOCX #99

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[6b528588](https://git.haulmont.com/platform/reports/commit/6b5285888ee6817477572b626e27cf9a28350c23) in **master** - Incorrect images resize with ${imageFileId:WxH} in DOCX #99
